clientsarea/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.org_info),
    path('upload', views.excel_upload, name='upload'),
]

to_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientsarea/models.py
from django.db import models
from users_auth.models import Organisation
from colorfield.fields import ColorField
from datetime import date


class OrderType(models.Model):
    type_label = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.type_label

    class Meta:
        verbose_name = "тип поручения"
        verbose_name_plural = "Типы поручений"


class StatusLabel(models.Model):
    label = models.CharField(max_length=255, primary_key=True, verbose_name='Метка', db_index=True)
    color = ColorField(default='#000000', verbose_name='Цвет метки')

    def __str__(self):
        return self.label

    class Meta:
        verbose_name = "тип статуса поручения"
        verbose_name_plural = "Типы статусов поручений"


class Order(models.Model):
    order_manager = models.CharField(max_length=255, verbose_name='Менеджер', blank=True, null=True)
    order_organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, verbose_name='Заказчик', blank=True, null=True)
    order_subdivision = models.CharField(max_length=255, verbose_name='Подразделение Заказчика', blank=True, null=True)
    order_contract = models.CharField(max_length=255, verbose_name='Договор с Заказчиком', blank=True, null=True)
    order_type = models.ForeignKey(OrderType, on_delete=models.CASCADE, verbose_name='Вид поручения', blank=True, null=True)
    order_full_num = models.CharField(max_length=255, verbose_name='Полный номер Поручения Экспедитора', db_index=True)
    order_date = models.DateField(verbose_name='Дата поручения', blank=True, null=True)
    order_pick_up_date_plan = models.DateField(verbose_name='Дата забора план', blank=True, null=True)
    order_pick_up_date_fact_carrier = models.DateField(verbose_name='Дата забора факт (по данным перевозчика)', blank=True, null=True)
    order_sender = models.CharField(max_length=1500, verbose_name='Наименование и Юр адрес отправителя', blank=True, null=True)
    order_from_addr = models.CharField(max_length=1500, verbose_name='Адрес отправки', blank=True, null=True)
    order_arr_date_plan = models.DateField(verbose_name='Дата доставки план (из Поручения)', blank=True, null=True)
    order_arr_date_fact = models.DateField(verbose_name='Дата доставки Факт', blank=True, null=True)
    order_recipient = models.CharField(max_length=1500, verbose_name='Наименование и юр адрес грузополучателя', blank=True, null=True)
    order_to_addr = models.CharField(max_length=1500, verbose_name='Адрес доставки', blank=True, null=True)
    cargo_name = models.CharField(max_length=1500, verbose_name='Наименование груза', blank=True, null=True)
    cargo_spaces_num = models.IntegerField(verbose_name='Количество грузовых мест', blank=True, null=True)
    cargo_weight_brut = models.CharField(max_length=255, verbose_name='Общий вес груза брутто (кг)', blank=True, null=True)
    cargo_weight_payed = models.CharField(max_length=255, verbose_name='Оплачиваемый вес, кг (по данным перевозчика)', blank=True, null=True)
    order_status = models.ForeignKey(StatusLabel, on_delete=models.CASCADE, verbose_name='Статус', blank=True, null=True)
    order_status_date = models.DateField(verbose_name='Дата обновления статуса', blank=True, null=True)
    order_location = models.CharField(verbose_name='Местоположение', max_length=255, blank=True, null=True)
    insurance = models.CharField(max_length=255, verbose_name='Страхование груза', blank=True, null=True)

    # order_rate = models.FloatField(verbose_name='Стоимость для Заказчика с учетом НДС (Ставка)')
    # order_rate_acked = models.BooleanField(default=True, verbose_name='Ставка согласована')
    # order_currency = models.CharField(max_length=255, verbose_name='Валюта ставки')
    # order_tax = models.IntegerField(default=20, verbose_name='НДС %')
    # order_tax_value = models.FloatField(verbose_name='Сумма НДС')
    # order_value_notax = models.FloatField(
    #     verbose_name='Стоимость для Заказчика в рублях без НДС (валюта пересчитывается по курсу)'
    # )
    # order_pre_rate = models.FloatField(verbose_name='Предварительно согласованная стоимость с Заказчиком ')
    # order_customs_procedure = models.CharField(max_length=255, verbose_name='Таможенная процедура', blank=True)
    # order_description = models.TextField(verbose_name='Примечания')
    # cargo_value = models.FloatField(verbose_name='Стоимость груза')
    # cargo_value_currency = models.FloatField(verbose_name='Валюта стоимости перевозимого груза')
    # cargo_package_type = models.CharField(max_length=255, verbose_name='Вид упаковки')
    # cargo_handling = models.CharField(max_length=255, verbose_name='Характер обработки груза')
    # cargo_danger = models.BooleanField(verbose_name='Опасный')
    # cargo_volume = models.CharField(max_length=255, verbose_name='Обьем, м3')
    # cargo_origin_country = models.CharField(max_length=255, verbose_name='Страна происхожения груза')
    # insurance_value = models.FloatField(verbose_name='Страховая сумма (RUB)')
    # insurance_premium = models.FloatField(verbose_name='Страховая премия')
    # insurance_premium_value = models.CharField(max_length=255, verbose_name='')
    # insurance_premium_currency = models.CharField(
    #     max_length=255, verbose_name='Валюта, в которой рассчитана страховая премия'
    # )
    # insurance_policy_number = models.CharField(max_length=255, verbose_name='Номер страхового полиса')
    # insurance_period = models.CharField(max_length=255, verbose_name='Период страхования')
    # transport_type = models.CharField(max_length=255, verbose_name='Тип транспорта')
    # transport_company = models.CharField(max_length=255, verbose_name='Транспортная компания')
    # transport_contract = models.CharField(max_length=255, verbose_name='Договор перевозчика')
    # transport_order_num = models.CharField(max_length=255, verbose_name='Номер поручения перевозчику')
    # transport_order_date = models.DateField(verbose_name='Дата поручения перевозчику')
    # transport_doc_type = models.CharField(max_length=255, verbose_name='Тип документа')
    # transport_doc_num = models.CharField(max_length=255, verbose_name='Номер перевозочного документа')
    # transport_doc_date = models.DateField(verbose_name='Дата документа')
    # transport_value = models.FloatField(verbose_name='Стоимость перевозчика')
    # transport_currency = models.CharField(max_length=255, verbose_name='Валюта перевозчика')
    # transport_tax = models.IntegerField(default=20, verbose_name='НДС %')
    # transport_tax_value = models.FloatField(verbose_name='Сумма НДС Поставщика в рублях')
    # transport_value_notax = models.FloatField(verbose_name='Стоимость Поставщика без НДС в рублях')
    # transport_doc_send_date = models.DateField(verbose_name='Дата выгрузки ПЭ Кириллом')
    # order_sub_num = models.IntegerField(verbose_name='Субномер')
    # order_pick_up_date_plan_carrier = models.DateField(verbose_name='Дата забора план (по данным перевозчика)')
    # order_delivery_terms = models.TextField(verbose_name='Условия поставки')
    # order_arr_date_plan_carrier = models.DateField(verbose_name='Дата доставки план (по данным перевозчика)')
    # cargo_code = models.CharField(max_length=255, verbose_name='Товарный код (маркировка)')
    # cargo_spaces_num_carrier = models.IntegerField(verbose_name='Колличество мест (по данным перевозчика)')
    # cargo_size = models.CharField(max_length=255, verbose_name='Габариты груза, см')

    def __str__(self):
        return f'Поручение от {self.order_organisation.name} №{self.order_full_num}'

    def attrs(self):
        for field in self._meta.fields:
            yield field.name, getattr(self, field.name)

    class Meta:
        verbose_name = "поручение"
        verbose_name_plural = "Поручения"

clientsarea/forms.py
from django import forms
from .models import Order
from users_auth.models import Organisation


class ExcelUpload(forms.Form):
    org = forms.ModelChoiceField(Organisation.objects.all(), label='Организация')
    file = forms.FileField(label='Файл Excel')


class OrdersFilter(forms.Form):
    order_num = forms.CharField()


class Menu(forms.Form):
    order = forms.ModelChoiceField(
        queryset=Order.objects.all().order_by('-order_status_date'),
        widget=forms.RadioSelect()
    )

    def filter(self, org=None, ord_num=None):
        if org is not None:
            self.fields['order'].queryset = self.fields['order'].queryset.filter(order_organisation=org)
        if ord_num is not None:
            self.fields['order'].queryset = self.fields['order'].queryset.filter(order_full_num__icontains=ord_num)

    def empty(self):
        self.fields['order'].queryset = None

clientsarea/views.py
import datetime
import logging
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import *
from .models import *
from users_auth.injector import inject_form
from django.http import HttpResponseForbidden
from django.core.exceptions import BadRequest


logger = logging.getLogger(__name__)

full_spreadsheet_upload_mapper = {
    'order_manager': (0, 'str'),
    'order_subdivision': (2, 'str'),
    'order_contract': (3, 'str'),
    'order_type': (4, 'str'),
    'order_num': (6, 'str'),
    'order_sub_num': (7, 'str'),
    'order_date': (8, 'date'),
    'order_pick_up_date_plan': (9, 'date'),
    'order_pick_up_date_fact_carrier': (10, 'date'),
    'order_sender': (13, 'str'),
    'order_from_addr': (14, 'str'),
    'order_arr_date_plan': (15, 'date'),
    'order_arr_date_fact': (17, 'date'),
    'order_recipient': (18, 'str'),
    'order_to_addr': (19, 'str'),
    'cargo_name': (20, 'str'),
    'cargo_spaces_num': (22, 'int'),
    'cargo_weight_brut': (25, 'str'),
    'cargo_weight_payed': (26, 'str'),
    'order_status': (42, 'str'),
    'insurance': (33, 'str')
}


manager_spreadsheet_upload_mapper = {

}


def get_or_create(model, **query):
    if not model.objects.filter(**query).exists():
        obj = model(**query)
        obj.save()
    return model.objects.get(**query)


def str_to_obj(data_item, order_key, model, model_key):
    value = data_item.pop(order_key, '')
    if value:
        data_item[order_key] = get_or_create(model, **{model_key: value})


def excel_upload(request):
    from clientsarea.excel_processor import ExcelProcessor
    context = inject_form(request)
    if request.user.is_staff:
        if request.method == 'POST':
            excel_form = ExcelUpload(request.POST, request.FILES)
            if excel_form.is_valid():
                excel_file = request.FILES['file']
                org = excel_form.cleaned_data['org']
                processor = ExcelProcessor(excel_file, 0)
                excel_data = processor.excel_data(full_spreadsheet_upload_mapper)
                new, updated, error = 0, 0, 0
                full_errors = list()
                for item in excel_data:
                    order_full_num = item.pop('order_num', '') + item.pop('order_sub_num', '')
                    item['order_full_num'] = order_full_num
                    str_to_obj(item, 'order_type', OrderType, 'type_label')
                    str_to_obj(item, 'order_status', StatusLabel, 'label')
                    order_arr_date_fact = item.get('order_arr_date_fact')
                    order_pick_up_date_fact_carrier = item.get('order_pick_up_date_fact_carrier')
                    if order_arr_date_fact:
                        item['order_status_date'] = order_arr_date_fact
                    elif order_pick_up_date_fact_carrier:
                        item['order_status_date'] = order_pick_up_date_fact_carrier
                    else:
                        item['order_status_date'] = datetime.date.today()
                    item['order_organisation'] = org
                    if order_full_num:
                        if Order.objects.filter(order_full_num=order_full_num).exists():
                            order = Order.objects.get(order_full_num=order_full_num)
                            changed = False
                            for attr_name, attr_value in item.items():
                                if order.__getattribute__(attr_name) != attr_value:
                                    order.__setattr__(attr_name, attr_value)
                                    changed = True
                            if changed:
                                try:
                                    order.save()
                                    updated += 1
                                except Exception as e:
                                    error += 1
                                    full_errors.append(order_full_num)
                                    logger.error(f'{order_full_num}: {e}')
                                    print(f'{order_full_num}: {e}')
                        else:
                            order = Order(**item)
                            try:
                                order.save()
                                new += 1
                            except Exception as e:
                                error += 1
                                full_errors.append(order_full_num)
                                logger.error(f'{order_full_num}: {e}')
                    else:
                        error += 1
                        logger.error(f'No order num in data: {item}')
                messages.info(request, f'Поручения успешно загружены.')
                messages.info(request, f'Добавлено новых поручений: {new}')
                messages.info(request, f'Обновлено поручений: {updated}')
                messages.info(request, f'Косячных поручений: {error}')
                if full_errors:
                    messages.info(request, f'Некорректные данные по поручениям:\n{", ".join(full_errors)}')

                logger.debug(f'File processed. {new} orders added, {updated} updated, {error} errors')
        else:
            excel_form = ExcelUpload()
        context['excel_form'] = excel_form
        return render(request, 'clientsarea/upload.html', context)
    else:
        return HttpResponseForbidden('Эта страница доступна только для сотрудников ООО "РТЛ-Таможенный оператор"')


def org_info(request):
    context = inject_form(request)
    if request.user.is_authenticated:
        if request.method == 'POST':
            menu = Menu(request.POST)
            ord_filter = OrdersFilter(request.POST)
            if not request.user.is_staff:
                if request.user.profile.org is None:
                    menu.empty()
                else:
                    menu.filter(org=request.user.profile.org)
            if menu.is_valid():
                order_pk = int(menu.data['order'])
                try:
                    order = Order.objects.get(pk=order_pk)
                except models.ObjectDoesNotExist:
                    print(order_pk, repr(menu.data))
                    raise
                # for key, value in order.attrs():
                #     if value is None:
                #         setattr(order, key, '')
                context['order'] = order
                context['order_pk'] = order_pk
            if ord_filter.is_valid():
                cd = ord_filter.cleaned_data
                menu.filter(ord_num=cd['order_num'])
        else:
            menu = Menu()
            ord_filter = OrdersFilter()
            if not request.user.is_staff:
                if request.user.profile.org is None:
                    menu.empty()
                else:
                    menu.filter(org=request.user.profile.org)

        context['menu'] = menu
        context['ord_filter'] = ord_filter
    return render(request, 'clientsarea/clientsarea.html', context)

to_site/templates/clientsarea/clientsarea.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
    <div id="info">
        <div id="user_info">
            <h2>{{ user.first_name }} {{ user.last_name }}</h2>
            <p><b>E-mail:</b> {{ user.email }}</p>
            <p><b>Тел.:</b> {{ user.profile.phone }}</p>
        </div>
        {% if user.is_staff %}
        <div class="upload_link">
            <a href="./upload">Загрузить общий Excel</a>
        </div>
        <div class="upload_link">
            <a href="./upload_manager">Загрузить таблицу менеджера</a>
        </div>
        {% endif %}
        <div id="org_info">
            <h2>{{ user.profile.org }}</h2>
            <p>{{ user.profile.org.address }}</p>
        </div>
    </div>
    <div id="orders">
        <div id="orders_menu">
            <h3>Поручения</h3>
            <form id="ord_filter" method="post" >
                {% csrf_token %}
                <input type="text" name="order_num" required="" id="id_order_num" placeholder="Поиск по номеру поручения">
                <input type="submit" value="Найти" />
            </form>
            <form id="short_info" method="post">
                {% csrf_token %}
                {% for pre in menu.fields.order.queryset %}
                <input class="hidden" type="radio" id="id_order_{{ pre.id }}" name="order" value="{{ pre.id }}" onChange="autoSubmit();"/>
                <label for="id_order_{{ pre.id }}" class="short_info_item grayblock {% if pre.pk == order_pk %}selected{% endif %}">
                    <div>
                        <div>Поручение №{{ pre.order_full_num }} от {{ pre.order_date|date:'d.m.Y' }}</div>
                        <div align="right"><span style="color: {{ pre.order_status.color }}">{{ pre.order_status.label }}</span></div>
                    </div>
                    <!--<div>{{ pre.order_from_addr }} -> {{ pre.order_to_addr }}</div>-->
                </label>
                {% endfor %}
            </form>
        </div>
        {% if order %}
        <div class="full_info_item" id="full_info_{{ order.pk }}">
            <div class="parameters">
                <h3>Параметры</h3>
                <div>
                    <div class="grayblock">
                        <p><b>Поручение</b> №{{ order.order_full_num }} от {{ order.order_date|date:'d.m.Y' }}</p>
                        <p><b>Вид поручения:</b> {{ order.order_type }}</p>
                        <p><b>Менеджер:</b> {{ order.order_manager }}</p>
                    </div>
                    <div class="grayblock">
                        <p><b>Заказчик:</b> {{ order.order_subdivision }} {{ order.order_organisation }}</p>
                        <p><b>Договор</b> №{{ order.order_contract }}</p>
                    </div>
                </div>
                <div>
                    <div class="grayblock">
                        <p><b>Отправитель:</b> {{ order.order_sender }}</p>
                        <p><b>Адрес отправки:</b> {{ order.order_from_addr }}</p>
                        <p><b>Планируемая дата отправления:</b> {{ order.order_pick_up_date_plan|date:'d.m.Y' }}</p>
                        <p><b>Фактическая дата отправления:</b> {{ order.order_pick_up_date_fact_carrier|date:'d.m.Y' }}</p>
                    </div>
                    <div class="grayblock">
                        <p><b>Получатель:</b> {{ order.order_recipient }}</p>
                        <p><b>Адрес доставки:</b> {{ order.order_to_addr }}</p>
                        <p><b>Планируемая дата доставки:</b> {{ order.order_arr_date_plan|date:'d.m.Y' }}</p>
                        <p><b>Фактическая дата доставки:</b> {{ order.order_arr_date_fact|date:'d.m.Y' }}</p>
                    </div>
                </div>
                <div>
                    <div class="grayblock">
                        <h3>Груз</h3>
                        <p><b>Наименование:</b> {{ order.cargo_name }}</p>
                        <p><b>Общий вес брутто:</b> {{ order.cargo_weight_brut }}</p>
                        <p><b>Оплачиваемый вес брутто:</b> {{ order.cargo_weight_payed }}</p>
                        <p><b>Количество мест:</b> {{ order.cargo_spaces_num }}</p>
                        <p><b>Страхование:</b> {{ order.insurance }}</p>
                    </div>
                    <div class="grayblock">
                        <p><b>Статус:</b> <span style="color: {{ order.order_status.color }}">{{ order.order_status.label }}</span></p>
                        <p><b>Дата:</b> {{ order.order_status_date }}</p>
                        <p><b>Последнее местоположение:</b> {{ order.order_location }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% else %}
    <div class="static">
        <h2>Для просмотра данной страницы необходима авторизация.</h2>
        <p>Если Вы являетесь клиентом ООО "РТЛ-Таможенный оператор", пожалуйста, авторизуйтесь.</p>
        <p>Если у Вас нет учетных данных, обратитесь за ними к Вашему менеджеру.</p>
    </div>
    {% endif %}
{% endblock %}

to_site/templates/clientsarea/upload.html
{% extends 'base.html' %}
{% block content %}
<form enctype="multipart/form-data" method="post" id="upload_form">
    <h2>Загрузить поручения из Excel</h2>
    {% csrf_token %}
    <div class="message" >
    {% for message in messages %}
        <h3 {% if message.tags == 'error' %} style="color: red" {% endif %}>{{message}}</h3>
    {% endfor %}
    </div>
    <div>
        <div class="upload_label">{{ excel_form.org.label }}:</div>
        <div class="upload_field">{{ excel_form.org }}</div>
    </div>
    <div>
        <div class="upload_label">{{ excel_form.file.label }}:</div>
        <div class="upload_field">{{ excel_form.file }}</div>
    </div>

    <input type="submit" value="Загрузить" />
</form>
{% endblock %}